### ISSUE TITLE
UX: reset pin cache after each usage

### ISSUE THREAD

**Issue by supermarin** [str4d/age-plugin-yubikey#132]
## What were you trying to do
Re-encrypt a large set of files (e.g. password store). 

## What happened

PIN cache expires several times during decryption and a seemingly successful script fails randomly mid way.

Ideally I'd want this to "just work" after first authentication, and see a couple of options:
1. Specify longer PIN cache manually
2. Reset PIN ttl after each age-plugin-yubikey invocation. I'm not sure if this is possible from the yubikey end since my knowledge with Yubi internals is close to 0.

Side note, I'd probably want 1.) Longer than 15s in any case, potentially for the whole seating  (until the next lock screen).

**Comment by str4d** [comment]
Were you using a published release of `age-plugin-yubikey`? If so, this is expected behaviour. If not, then this might be a solvable issue: what kind of YubiKey were you using?

> PIN cache expires several times during decryption and a seemingly successful script fails randomly mid way.

We have already been working on enabling this (as much as is possible for an ephemeral binary) for the 0.4.0 release; you can try building from the current `main` branch to test it. There are some notable limitations on it, [documented in the README](https://github.com/str4d/age-plugin-yubikey#agent-support).

> 1. Specify longer PIN cache manually

There is no length that can be specified here. If the PIN policy is "once" then the fact that a PIN was entered will be cached inside the YubiKey as long as the conditions noted in the README don't occur.

> 2. Reset PIN ttl after each age-plugin-yubikey invocation. I'm not sure if this is possible from the yubikey end since my knowledge with Yubi internals is close to 0.
>
> Side note, I'd probably want 1.) Longer than 15s in any case, potentially for the whole seating (until the next lock screen).

The 15 second timer you may be thinking of is for the "Cached" touch policy. No such policy or TTL exists for PINs; they only have the listed policies of "Never", "Once", or "All". The _effective TTL_ for the "Once" policy depends on a bunch of things however, as documented in the README.

**Comment by supermarin** [comment]
> Were you using a published release of age-plugin-yubikey? If so, this is expected behaviour. If not, then this might be a solvable issue: what kind of YubiKey were you using?

Nope, I'm building from source (commit bf437663af22ba6492fc738d3e1bdf6d6cc2a00a).

> The 15 second timer you may be thinking of is for the "Cached" touch policy. No such policy or TTL exists for PINs; they only have the listed policies of "Never", "Once", or "All". The effective TTL for the "Once" policy depends on a bunch of things however, as documented in the README.

Omg, just re-read this and ... probably shouldn't be filing issues at 7AM. I'll update the issue title and my first post. What I've mixed up is *PIN* policy and *touch* policy.

Here are repro steps in detail:
1. `for f in **/*.age; do age -i <(age-plugin-yubikey -i) -d $f; done`
2. Input PIN
3. Touch the key
4. Everything works as expected, except: after 15s, the key starts blinking again requiring a touch. The consecutive loop runs fail. 
5. After a key touch, the loop proceeds and gets back to step 3 after 15s.

No other conditions from the README are met that would cause key invalidation.
Think I'd prefer to keep "Cached" vs "Never" for security purposes.
According to [Yubikey docs](https://docs.yubico.com/yesdk/users-manual/application-piv/pin-touch-policies.html) this might not be fixable from your side, but maybe a README entry would be helpful to point this out.

**Comment by str4d** [comment]
> 4. Everything works as expected, except: after 15s, the key starts blinking again requiring a touch. The consecutive loop runs fail.

This is expected behaviour for the "Cached" touch policy. The 15-second cache timeout is built into the YubiKey's internal firmware, inside its security boundary; there is nothing we can do in `age-plugin-yubikey` or any other application to alter its duration.

The most we could do is ensure that `age-plugin-yubikey` doesn't time out waiting for the user to touch the YubiKey (IDK if it does off the top of my head), but when decrypting in a loop with a "Cached" touch policy, that means the script will block indefinitely every 15 seconds.

**Comment by supermarin** [comment]
> This is expected behaviour for the "Cached" touch policy. The 15-second cache timeout is built into the YubiKey's internal firmware, inside its security boundary; there is nothing we can do in age-plugin-yubikey or any other application to alter its duration.
Yep understood, thanks for putting the effort to explain.

> The most we could do is ensure that age-plugin-yubikey doesn't time out waiting for the user to touch the YubiKey (IDK if it does off the top of my head)
That sounds like a great idea

**Comment by str4d** [comment]
> The most we could do is ensure that `age-plugin-yubikey` doesn't time out waiting for the user to touch the YubiKey (IDK if it does off the top of my head)

I confirmed that `age-plugin-yubikey` doesn't implement any timeout here, and AFAIR never has. We previously printed a message asking the user to touch the yubikey after entering the PIN if we knew it would be needed, but that was removed in 345c155bb423f6ffd64842ee0fa2689ef5ba2f14 to allow age clients to handle it instead. (`rage 0.8.0` implemented this by displaying a message after 10 seconds, but does not implement a timeout AFAIR.)

So the current behaviour of this plugin is to request the PIN if needed, and then immediately tell the YubiKey to decrypt; the YubiKey then determines whether a touch is necessary or cached, and blinks its LED if a touch is needed. There is nothing more I can do in this plugin; the behaviour is as expected for this touch policy.
