### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by supermarin** [str4d/age-plugin-yubikey#160]
There's quite a few UX issues with age&yubikey and it seems like there's been very little maintainer output on this project (last commit 9 months ago), age, and yubikey-agent (last commit 2 years ago).

@filosottile @str4d  Would you please provide any input on short to mid term plans?

**Comment by str4d** [comment]
No, this project is not abandoned.
- While a lack of commits can imply abandonment, that is not on its own a reliable inference. It can also imply a stable project that doesn't need too much attention. A lot of work went into the 0.3.0 release (published in May 2022) in order to move the plugin from "beta" to "stable", which front-loaded most of what would otherwise have been a drip-feed of improvements over time.
- "Maintainer output" is nebulous, particularly for something like the age ecosystem that has "project activity" spread across several different places. If you count activity only on this repository, then besides replying to one UX issue in December, I haven't done much. But had you looked a week or so later, you'd have seen a flurry of activity here. In the time since the last non-trivial commit I pushed to this repository (April last year, for the 0.4.0 release), I've been spending my age-related development time on [`str4d/rage`](https://github.com/str4d/rage), both on a client that can use this plugin, and the crates that this plugin depends on. In particular, I've spent the last two months working towards the `rage 0.10` release (which I hope to get out in a week or so), after which I would have come here to update this crate to the next release of `age-plugin`, and likely tried to make some progress on the open UX issues.

For this plugin specifically, the main issue I have is that the most of the current UX issues people are running into are out of my control:
- Problems caused by my dependencies reporting generic error information that I cannot act on. I have made PRs upstream to those dependencies to improve occurrences of this as I encounter them, but it's not something I have direct control over.
- Problems that are unable to be solved by an ephemeral plugin binary and fundamentally requiring a long-runing daemon that can hold a lock on the YubiKey (which means coordinating with all other users wanting to use it for SSH etc, thus being outside the scope of `age-plugin-yubikey`). I tried to address as much of this as I could in the latest release of this crate (0.4.0), but I am bound by the limitations of the PSCS protocol and hardware implementations.

I would also like to remind everyone that, like many open source developers, I am not paid to work on this. The time I have to work on age-related projects (necessarily split between the `rage`, `age`, and `age-plugin-yubikey` crates) is shared with all the rest of my personal free time, which I haven't had a lot of in the past few years. If lack of visible progress on UX issues is an existential concern to some users, then the easiest way to address their concerns is for those users to contribute time to investigation, patches and/or reviews.
