### ISSUE TITLE
Question: Is it secure to commit the identity and .age file publicly?

### ISSUE THREAD

**Issue by MartinLoeper** [str4d/age-plugin-yubikey#179]
I am using this tool in conjunction with agenix and I am wondering whether it is secure to:

- commit the ciphertext which is generated by age, i.e. the .age file
- commit the age-plugin-yubikey's identity file

to a git repository.

Is there something confidential inside the identity file?
I see a lot of metadata and a string like: *AGE-PLUGIN-YUBIKEY-XXXXXXXXXXXXXXXXXXXXXX*

As far as I understand the key material is stored in the yubikey's PIV slot, so the identity file is not inherently confidential, is it?

**Comment by str4d** [comment]
It depends on what you consider to be confidential in your use case. (As usual, IANYC.)

> * commit the ciphertext which is generated by age, i.e. the .age file

If the git repository is public, the ciphertexts are also public, which has two consequences:
- Anyone with access to the git repo and access to one of the age identities is able to obtain the plaintext. If an age identity is compromised, you can't hide the earlier committed ciphertext. This is no different to committing any other kind of encrypted file to a repository.
- The ciphertext stanza generated by `age-plugin-yubikey` contains a `tag` value identifying the recipient that the ciphertext is encrypted to (it is used to identify which YubiKey the file should be decrypted with). Committing the age ciphertext means revealing this tag.

An `age-plugin-yubikey` identity contains a stub with the following information:
https://github.com/str4d/age-plugin-yubikey/blob/5159577135c45a5a01de727e333d1548247dadfd/src/key.rs#L417-L422

You can see the `tag` present there (matched to the ciphertext stanza), but it also contains the details needed to find the correct identity on the correct YubiKey. `slot` doesn't particularly matter if it is exposed (there are only 20), and `tag` is only 4 bytes so there are likely global collisions, but the YubiKey serial is also present, and depending on your context that may be sensitive information.

However, as far as whether committing the ciphertext and identity file enables someone to decrypt the file: in general no, you need to possess the actual YubiKey in order to decrypt the file. Technically you can import keys into a PIV applet, so the key _could_ exist outside the YubiKey, but `age-plugin-yubikey` does not (currently) support this use case, so if you're generating the identity with `age-plugin-yubikey` then the private key only exists on the YubiKey.

**Comment by MartinLoeper** [comment]
Thanks @str4d, very much appreciating your thorough writeup and explanations! This helps me immensely to evaluate whether I can put certain things into one of our company's internal VCS.
