### ISSUE TITLE
Does not build with rust 1.80.0

### ISSUE THREAD

**Issue by VlkrS** [str4d/age-plugin-yubikey#182]
## Environment

* OS: OpenBSD
* age-plugin-yubikey version: 0.4.0

## What were you trying to do

Building with Rust 1.80.0

## What happened

To make age-plugin-yubikey build with rust 1.80.0 the time crate needs to be updated, and probably several other dependencies as well. Do you think it's possible to bump the dependencies and put the result through CI to see if there's any fallout?

**Comment by semarie** [comment]
for reference about the time crate breakage, see https://github.com/rust-lang/rust/issues/125319

**Comment by str4d** [comment]
https://github.com/rust-lang/rust/issues/125319#issuecomment-2120809372 implies that `time 0.3.36` or later is required for the fix. `time 0.3.24` bumped its MSRV to 1.67, which means in order to fix compilation with Rust 1.80, I'm also forced to bump MSRV of this crate to 1.67.

I'll see if I can limit the breakage to there.

**Comment by VlkrS** [comment]
Thank you!
