### ISSUE TITLE
Touching YK while prompting PIN causes error

### ISSUE THREAD

**Issue by FiloSottile** [str4d/age-plugin-yubikey#37]
## Environment

* OS: macOS
* age-plugin-yubikey version: 0.1.0

## What were you trying to do

I accidentally touched the YK too soon while pressing enter on the PIN prompt, so the touch arrived before the PIN. I expected it to just ignore the touch.

## What happened

```
[age-plugin-yubikey] Please insert YubiKey with serial 15413828
[age-plugin-yubikey] Enter PIN for YubiKey with serial 15413828
[age-plugin-yubikey] Enter value:
age: error: age-plugin-yubikey: "Invalid YubiKey PIN"
```

**Comment by str4d** [comment]
I'm pretty sure what happened here is that the early touch caused the YubiKey OTP to be "typed in" as the PIN (since it generates the OTP string followed by a newline). I'm supposedly connected to the YubiKey at the time I ask for the PIN, but maybe that's not sufficient to "lock" the key and prevent it from being OTP-able?

What I can do here however is detect this case. An OTP string is too long to be a valid PIN, so I could check the passphrase length and prefix first, and if it looks like an OTP string I can ignore it and re-request the PIN.

**Comment by str4d** [comment]
Reading your issue more closely, I see that you had already typed in your actual PIN, and this was just a race condition between the touch and enter. I still think the touch triggered the OTP typing, but in that case it would have just appended itself to your PIN, resulting in a too-long PIN (which for version 0.1.0 was just reported as "Invalid YubiKey PIN", while for 0.2.0 would show "size error").

I've opened #46 to detect a PIN that is too short or too long, and ask the user to re-enter the PIN. It also specifically detects the "touched before typing" OTP case.
