### ISSUE TITLE
UX: Print message to touch the Yubikey when touch expected

### ISSUE THREAD

**Issue by mihaigalos** [str4d/age-plugin-yubikey#68]
I currently get no prompt to touch the Yubikey when decrypting files.
This diff with additions doesn't work:

```diff
diff --git a/src/key.rs b/src/key.rs
index 01b5209..0855f3f 100644
--- a/src/key.rs
+++ b/src/key.rs
@@ -521,6 +521,9 @@ impl Connection {
             _ => false,
         };
 
+        if needs_touch {
+            println!("👆 Please touch the YubiKey.");
+        }
         // The YubiKey API for performing scalar multiplication takes the point in its
         // uncompressed SEC-1 encoding.
         let shared_secret = match decrypt_data(
```
```bash
$ cat foo.txt.age | ./rage/rage -d -i age-yubikey-identity-c60b9683.txt > foo.txt
Error: invalid response

[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report                            ]
```
I had a look at the code but couldn't see if you're redirecting stdout which I assume is used to communicate with `rage` and gets polluted by the println.

**Comment by str4d** [comment]
Yeah, you can't use `println` in plugins, because stdout it's used to communicate with the age client (hence the `incomplete response` error as it tries to interpret the string as an IPC command.

I had added the direct message you're referring to during the development of 0.3.0, but removed it shortly before release after working out a more general solution (https://github.com/str4d/age-plugin-yubikey/issues/44#issuecomment-1114074172). Now, if you use `rage 0.8.0`, it will print out a `Waiting on age-plugin-yubikey...` message after ten seconds of inactivity, which serves to remind the user to take action, without causing the terminal to be filled with repeated messages for repeated touches (e.g. if decrypting many files using a script).
