### ISSUE TITLE
x25519 support for Yubikey

### ISSUE THREAD

**Issue by v3rm0n** [str4d/age-plugin-yubikey#70]
We would like to combine Age and Yubikey, but we are interested in using curves that are not currently supported with this plugin like x25519, secp521r1 etc.
It's technically feasible, over the openpgp smartcard application on the Yubikey, but I see that this plugin uses the Yubikey Rust library which only has PIV support so it seems pretty difficult to add this functionality to the current plugin.
So I guess my question is: is this something you are interested in as well or does it make more sense if we create a new plugin for it?

**Comment by str4d** [comment]
This age plugin is tailored to the YubiKey PIV applet (though it also happens to work with PIV applets generally). Adding support for additional cryptographic primitives within the PIV applet is doable but increases complexity and maintenance burden (I'd previously had RSA support, but removed it to simplify the UX; it might end up being reintroduced in a restricted way for a specific default-disabled specialized usage for #62). It's also restricted by the slow-moving nature of the PIV specification and its effect on hardware support for alternative curves. But for the intended use case of this plugin, P256 is a perfectly fine curve to rely on, so that doesn't really matter.

I expect it would make the UX more confusing to add support for additional smartcard applications, because then you need to deal with the fact that the different applets need to be selected separately, have potentially different PINs (and PIN requirements, see e.g. #72), and have potentially different interaction models. I think this is likely more easily handled with a separate plugin.

Note that it's perfectly fine to have multiple different age plugins that can generate or decrypt the same kinds of recipient stanzas (e.g. this plugin's `piv-p256` stanzas, or the native `x25519` stanzas for interoperability with native age recipients). This was an intentional part of the age plugin design, which e.g. we plan to leverage to enable `yubikey-agent` to implement agent-like handling of YubiKey identities generated by `age-plugin-yubikey`.

It's also reasonable to consider the possibility where an idea is experimented with and tested in one plugin, and then later merged into a more widely-used plugin. I'm not saying that I _would_ merge OpenPGP smartcard support into `age-plugin-yubikey` at some point, but that it would be easier to consider doing so if the UX concerns had already been figured out in another plugin.

**Comment by v3rm0n** [comment]
Thanks for your reply!
Makes sense. We have started with our own plugin which uses OpenPGP to get x25519 https://github.com/Producement/age-yubikey-pgp . Currently you can only combine with the Dart implementation of age https://github.com/Producement/dage but soon I'm planning to implement the plugin spec so it can be used with any implementation.
