### ISSUE TITLE
UX: request for clarification - does "--identity" print secret data?

### ISSUE THREAD

**Issue by antifuchs** [str4d/age-plugin-yubikey#73]
## What were you trying to do

I'm trying to figure out how to use age-plugin-yubikey to safely store my nix secrets with [agenix](https://github.com/ryantm/agenix). agenix requires an "identity" file be present to decrypt the stored secrets, and I'm trying to figure out if it's safe to store output of `age-plugin-yubikey --identity` in the repo (assuming it's akin to the gpg "key grips" you get with smart cards), or if that contains any of the secret data that would otherwise rest safely on my yubikey.

## What happened

I was hoping the docs could clear that up, but they refer to "identities stored on yubikeys" and then show how to print an identity in  https://github.com/str4d/age-plugin-yubikey#configuration; so it would be good to have clarification on how secret the information printed really is.

**Comment by str4d** [comment]
An `age-plugin-yubikey` identity is similar to a key grip. It contains:

- The serial of the YubiKey on which the identity's secret key resides.
- The ID of the slot on that YubiKey's PIV applet in which the identity's secret key is stored.
- A 4-byte digest (a "tag") of the corresponding recipient, so we can detect if the secret key in the slot matches what it was when the identity was generated.

The tag enables an identity to be linked to a recipient (with 2^-16 collision probability, which is possible across the entire ecosystem but unlikely within your own personal keys), so that's one thing to consider. Likewise the YubiKey serial might make the identity linkable to other key grips, which might be relevant to some threat models.

But there's nothing in the identity that compromises the secret key. That is generated in the YubiKey, and never leaves it.

**Comment by antifuchs** [comment]
Perfect, that's just as I'd hoped! Thank you!
