### ISSUE TITLE
"Could not open YubiKey" error message while inserted, after decrypting with GPG

### ISSUE THREAD

**Issue by bcvanmeurs** [str4d/age-plugin-yubikey#82]
Hi I encountered this bug/issue while trying to decrypt an age encrypted file.

Steps to reproduce:
1. Encrypt a file with Age
2. Encrypt another file with GPG `gpg --encrypt --armor`
3. Decrypting the age encrypted file works as expected
4. Decrypt the GPG encrypted file with GPG key on yubikey `gpg --decrypt` (Yubikey asks for pin on GPG interface)
5. Decrypting the age encrypted file fails with the message: 
    ```
    Please insert YubiKey with serial XXX (press [1] for "YubiKey is plugged in" or [2] for "Skip this YubiKey") # select 1
    Could not open YubiKey. Please insert YubiKey with serial XXX (press [1] for "YubiKey is plugged in" or [2] for "Skip this YubiKey")
    ```
Workaround: reinsert the yubikey and decryption works as expected.

Any idea why this might happen?

By the way, thanks for making and maintaining this plugin, it is really nice.

**Comment by bcvanmeurs** [comment]
I think I found the reason here: 
https://github.com/Yubico/yubikey-manager/issues/35#issuecomment-734135905

> CCID based commands (such as piv, oath, and openpgp) don't work after running gpg. This is in most cases due to scdaemon (which is part of gpg) holding exclusive access to the YubiKey (details here: https://dev.gnupg.org/T2440 possible workaround: setting a timeout in scdaemon.conf as described here: https://forum.yubico.com/viewtopicb85f.html?p=7513).

I confirmed this by running `gpgconf --reload scdaemon` and the connection to piv works again.

ykman has a workaround by killing `scdaemon` when it can't connect, see below. Yubico Authenticator [has a similar thing](https://forum.yubico.com/viewtopicb85f.html?p=7513#p7513)

Do you think it is worth implementing something similar in this plugin? I am happy to start a PR if you think this is useful.

## reference to ykman

[source](
https://github.com/Yubico/yubikey-manager/blob/f00c5078967aee452bff873fea72b2c4c4780d77/ykman/pcsc/__init__.py#L94-L100)

```python
    def _open_smartcard_connection(self) -> SmartCardConnection:
        try:
            return ScardSmartCardConnection(self.reader.createConnection())
        except CardConnectionException as e:
            if kill_scdaemon():
                return ScardSmartCardConnection(self.reader.createConnection())
            raise e
```
with [kill_scdaemon()](https://github.com/Yubico/yubikey-manager/blob/f00c5078967aee452bff873fea72b2c4c4780d77/ykman/pcsc/__init__.py#L129-L152):

```python
def kill_scdaemon():
    killed = False
    try:
        # Works for Windows.
        from win32com.client import GetObject
        from win32api import OpenProcess, CloseHandle, TerminateProcess

        wmi = GetObject("winmgmts:")
        ps = wmi.InstancesOf("Win32_Process")
        for p in ps:
            if p.Properties_("Name").Value == "scdaemon.exe":
                pid = p.Properties_("ProcessID").Value
                handle = OpenProcess(1, False, pid)
                TerminateProcess(handle, -1)
                CloseHandle(handle)
                killed = True
    except ImportError:
        # Works for Linux and OS X.
        return_code = subprocess.call(["pkill", "-9", "scdaemon"])  # nosec
        if return_code == 0:
            killed = True
    if killed:
        sleep(0.1)
    return killed
```

**Comment by str4d** [comment]
I don't know enough about `scdaemon` to know if killing it is "safe", especially when there may be ongoing operations. Reading the GnuPG issue, it seems like `gpgconf --reload scdaemon` would be safer, which per [the `gpgconf` manpage](https://www.gnupg.org/documentation/manuals/gnupg/Invoking-gpgconf.html#Invoking-gpgconf) is equivalent to sending a SIGHUP to `scdaemon`. So could we do the latter (i.e. not relying on the presence of `gpgconf`)? My assumption is that a SIGHUP is safer than a kill, because `scdaemon` can internally decide whether to finish serving any current requests before reloading.

**Comment by str4d** [comment]
Welp, it looks like `scdaemon` registers a SIGHUP handler that [logs it will do something and then does nothing](https://github.com/gpg/gnupg/blob/25ae80b8eb6e9011049d76440ad7d250c1d02f7c/scd/scdaemon.c#L1014-L1018). This behaviour has been present and unaltered since 2004-04-13: https://github.com/gpg/gnupg/commit/e950b01ff56c86d8e04b75a7bac4234afc939199

Instead, let's trace what `gpgconf --reload scdaemon` does:
- Finds the index for the `scdaemon` component and calls `gc_component_reload` ([source](https://github.com/gpg/gnupg/blob/25ae80b8eb6e9011049d76440ad7d250c1d02f7c/tools/gpgconf.c#L772-L785)).
- `gc_component_reload` calls `do_runtime_change` with `killflag = 0` ([source](https://github.com/gpg/gnupg/blob/31c0aa2ff37f662c6391885d61ffd46ec3062e5a/tools/gpgconf-comp.c#L1029-L1034)).
- `do_runtime_change` calls the [`runtime_change` handler](https://github.com/gpg/gnupg/blob/25ae80b8eb6e9011049d76440ad7d250c1d02f7c/tools/gpgconf-comp.c#L630-L632) for the component, if it exists ([source](https://github.com/gpg/gnupg/blob/31c0aa2ff37f662c6391885d61ffd46ec3062e5a/tools/gpgconf-comp.c#L1012-L1017)), which in this case is [`scdaemon_runtime_change`](https://github.com/gpg/gnupg/blob/25ae80b8eb6e9011049d76440ad7d250c1d02f7c/tools/gpgconf-comp.c#L669-L671).

And here we learn that ["For scdaemon kill and reload are synonyms"](https://github.com/gpg/gnupg/blob/25ae80b8eb6e9011049d76440ad7d250c1d02f7c/tools/gpgconf-comp.c#L777) (which after writing this comment, I now notice is in fact documented in the manpage for `gpgconf --kill`). What they do here is send `scd killscd` to `gpg-agent`, conditional on both `gpg-agent` running and `GETINFO scd_running` evaluating to true (to avoid starting `scdaemon` immediately before stopping it). `killscd` causes [an internal `stopme` flag to be set and the Assuan connection to be closed](https://github.com/gpg/gnupg/blob/25ae80b8eb6e9011049d76440ad7d250c1d02f7c/scd/command.c#L2083-L2084), which subsequently causes `scd_command_handler` to [call `scd_exit(0)`](https://github.com/gpg/gnupg/blob/25ae80b8eb6e9011049d76440ad7d250c1d02f7c/scd/command.c#L2420-L2421).

If we go back and look at the registered signal handlers again, we can see that SIGINT does precisely what we need, as it calls `scd_exit(0)` synchronously ([source](https://github.com/gpg/gnupg/blob/25ae80b8eb6e9011049d76440ad7d250c1d02f7c/scd/scdaemon.c#L1053-L1058)). So AFAICT there is no reason to use `pkill -9 scdaemon`, and we should instead use `pkill -INT scdaemon` to allow it to perform its final cleanups.

`pkill -TERM scdaemon` would allow existing connections to terminate gracefully, but given that `gpgconf --reload scdaemon` does not do this, I don't see why we need to either. There's maybe an argument that `gpgconf --reload scdaemon` has more "user intent", but there's nothing stopping anyone from calling it in a script or from another program, and I don't see why sending signals to `scdaemon` directly should be treated any different.
